### ISSUE TITLE
Feature request: support to .razor files

### ISSUE THREAD

**Issue by danfma** [belav/csharpier#895] opened 2023-05-09 14:38 UTC
It would be nice if the current csharpier could support Blazor files too.

**Comment by belav** [comment] 2023-05-10 01:51
I haven't actually used .razor files, but from my googling it seems they are handled the same as .cshtml files as far as .net is concerned. Assuming that's true this is a duplicate of https://github.com/belav/csharpier/issues/35

**Closed** 2023-05-22 19:58 UTC
