### ISSUE TITLE
Support VSCode Format on Save Modifications Only Mode

### ISSUE THREAD

**Issue by cl3m** [belav/csharpier#1193] opened 2024-03-06 09:36 UTC
**Environments**
- IDE Version: VSCode 1.87.0
- Extension Version: 1.6.0
- CSharpier Version:  0.27.3
- Operating System: macOS 14.2.1

**Steps to reproduce**

Use `"editor.formatOnSaveMode": "modifications"` in vscode setting.

**Expected behavior**

Format only the modified part of the file.

**Actual behavior**

Does not format at all. You need to use `"editor.formatOnSaveMode": "file"` which format the whole file.

**Comment by belav** [comment] 2024-03-08 20:59
Duplicate of #659

**Closed by belav** 2024-03-08 20:59 UTC
