### ISSUE TITLE
Support .editorconfig file

### ISSUE THREAD

**Issue by mehdihadeli** [belav/csharpier#800] opened 2023-01-22 10:52 UTC
Hi,
I think it is better we have ability of using `.editorconfig` instead of `.csharpierrc` like something existing in the [prettier](https://prettier.io/docs/en/configuration.html#editorconfig)

**Comment by belav** [comment] 2023-01-22 16:13
Duplicate of #630

**Closed by belav** 2023-01-22 16:13 UTC
