### ISSUE TITLE
Enforce trailing comma

### ISSUE THREAD

**Issue by marcospgp** [belav/csharpier#1285] opened 2024-06-08 12:18 UTC
Currently both including and not including the last comma in a list is allowed, such as:

```
            var mesh = new Mesh()
            {
                name = name,
                vertices = vs.ToArray(),
                triangles = ts.ToArray(),
                uv = uvs.ToArray(), // Comma here.
            };
```

```
            var mesh = new Mesh()
            {
                name = name,
                vertices = vs.ToArray(),
                triangles = ts.ToArray(),
                uv = uvs.ToArray() // No comma here.
            };
```

This should not be ambiguous, and in accordance with Prettier the trailing comma should be enforced.

**Comment by belav** [comment] 2024-06-08 16:12
Duplicate of #668

**Closed by belav** 2024-06-08 16:12 UTC
