### ISSUE TITLE
CSharpier plugin hanging Rider IDE

### ISSUE THREAD

**Issue by danfma** [belav/csharpier#1021] opened 2023-11-16 12:10 UTC
After updating to csharpier 0.26.+ my IDE started to get frozen. I realized that the csharpier still works very well when running directly from the CLI, so I can only imagine that this might be a problem with the plugin now.

> The 1.3.11-beta1 version is working as expected with this newer version of csharpier!

**Comment by LensArt** [comment] 2023-11-16 18:25
Me and my colleagues experience the same issue, maybe these logs help? 
[threadDump-20231116-191525.txt](https://github.com/belav/csharpier/files/13381326/threadDump-20231116-191525.txt)

However it indeed seems to be fixed with the 1.3.11-beta version.
Any plan to release this soon?

**Comment by belav** [comment] 2023-11-18 16:53
I'm closing this as a duplicate of #926 

@LensArt I was hoping to get a new GRPC version of the plugins done by now, so kind of forgot about that beta. 

I believe I know how to resolve the issues that are causing the various freezes/hangs in the IDEs and hope to have a fix out in the next few days. If the problem is what I think it is then I'm not sure why the beta would fix it. But I plan on incorporating that as well.

**Closed by belav** 2023-11-18 16:53 UTC
