### ISSUE TITLE
How can I make CSharpier work with Visual Studio?

### ISSUE THREAD

**Issue by Dennis-N8** [belav/csharpier#1249] opened 2024-04-30 16:36 UTC
**Environments**
- IDE Version: Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.9.6
- Extension Version: 1.7.1
- CSharpier Version:  0.28.2
- Operating System: Windows 10 Pro
- .csharpierrc Settings: Not present
- .editorconfig Settings: Not present

**Log Output**
[Info - 4/30/2024 19:30:53] Formatting started for C:\...\CarController.cs using CSharpier 0.28.2
[Warn - 4/30/2024 19:30:53] Failed posting to the csharpier server. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: The requested address is not valid in its context 127.0.0.1:0
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at CSharpierProcessServer.formatFile(FormatFileParameter parameter)
[Info - 4/30/2024 19:30:53] Formatted in 1ms

**Steps to reproduce**
Right click inside any .cs file in Visual Studio and select 'Format With CSharpier'

**Expected behavior**
It should work as expected
 
**Actual behavior**
It doesn't format the .cs file.

**The output of 'dotnet --list-sdks':**
7.0.401 [C:\Program Files\dotnet\sdk]
8.0.204 [C:\Program Files\dotnet\sdk]

**global.json content**
{ "sdk": { "version": "7.0.401" } }

With and without `global.json` the CSharpier extension doesn't work.

Also, how can I make the CSharpier work with latest dotnet sdk regardless which sdk version is in global.json?

**Comment by belav** [comment] 2024-05-01 00:30
Based on the fact it is trying to connect using port 0, I believe it is failing to start the csharpier server but not detecting that it failed to start. Can you enable debug logging? That will hopefully point me in the direction of the problem.

If you need to get things working in the short term using csharpier 0.27.x will use the older style of communication. I don't see an obvious way to downgrade the extension to 1.5.x which would also use the older style of communication with 0.28.x

![image](https://github.com/belav/csharpier/assets/3606529/10648491-c9f2-4a53-b3d9-bd018de0da48)

**Comment by Dennis-N8** [comment] 2024-05-02 13:34
Sometimes it starts.

![image](https://github.com/belav/csharpier/assets/128690326/307a3f29-4cef-4ba9-8aa2-b58289344545)

What I did differently now is:
1) ran the command: `dotnet tool update csharpier`
2) deleted the 'global.json' file
3) closed the Visual Studio a few times after that.

I'm not sure which of these commands helped. Maybe both.

**Comment by Dennis-N8** [comment] 2024-05-02 13:41
The difference between these two is: in first screenshot it doesn't check for 'dotnet-tools.json'.
The solution which contains the `.config` directory (with `dotnet-tools.json`) has several C# projects.

![image](https://github.com/belav/csharpier/assets/128690326/715695ce-bb02-4b0d-91ad-5f2643445044)

**Comment by Dennis-N8** [comment] 2024-05-03 09:06
But this solution is temporary. After I restart the computer - it doesn't work again.

**Comment by belav** [comment] 2024-05-03 16:09
I did find a path through the code that would cause the extension to try formatting with 0 as a port, but it should still produce a warning. If csharpier fails to start after 2 seconds it was giving up but not flagging it as unable to start. I believe 1.7.2 will prevent the extension from trying to call csharpier on port 0, and instead log `"CSharpier process failed to start. Formatting cannot occur.`, which still doesn't tell us why it isn't starting for you.

The output of CSharpier should always start with this line, maybe your output is getting cleared somehow?
[Info - 5/3/2024 10:44:18 AM] Starting

You can try running the command the extension uses to start csharpier, it would be
```
C:\Users\[UserName]\AppData\Local\CSharpier\[Version]\dotnet-csharpier.exe --server
```

You should see info from kestrel starting up and which port it is on.


I'm not sure if the global.json file would affect how the extension makes that call, I don't set `WorkingDirectory` on `ProcessStartInfo` so I believe it uses the directory that contains dotnet-csharpier.

If all else fails you could also try debugging the extension

https://github.com/belav/csharpier/blob/main/Src/CSharpier.VisualStudio/CONTRIBUTING.md has some basic instructions

https://github.com/belav/csharpier/blob/main/Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessServer.cs#L38 is where the extension is trying to start csharpier.

**Comment by Dennis-N8** [comment] 2024-05-04 13:52
So I closed the Visual Studio and re-opened it. Now the extension version is 1.7.2

I got this message: 
![image](https://github.com/belav/csharpier/assets/128690326/f58ec560-5f53-4fb9-841e-4ba76d2754af)


And this:
![image](https://github.com/belav/csharpier/assets/128690326/268894f8-6e95-4352-90ab-9b9e3f41301f)

**Comment by Dennis-N8** [comment] 2024-05-04 14:06
Deleting the global.json, running the 'dotnet tool update csharpier' and reopening VS helps.

**Comment by Dennis-N8** [comment] 2024-05-04 14:08
Maybe on timeout try to start the process on a default port(s)?

**Comment by belav** [comment] 2024-05-06 13:41
Can you run this to see what it does? It already tries to find a free port when starting
```
C:\Users\[UserName]\AppData\Local\CSharpier\[Version]\dotnet-csharpier.exe --server
```

**Comment by Dennis-N8** [comment] 2024-05-06 16:34
![image](https://github.com/belav/csharpier/assets/128690326/20aa599f-9db3-46cc-aa78-bc70b4127b00)


![image](https://github.com/belav/csharpier/assets/128690326/ad9735e9-004c-406a-8d71-4103fc9cd27b)

**Comment by Dennis-N8** [comment] 2024-05-06 16:37
So I closed and reopened the Visual Studio while the command was running in console.
And I could format the code.

Strange.

**Comment by Dennis-N8** [comment] 2024-05-08 05:36
Today running the command `dotnet csharpier --server` before opening the project in Visual Studio helped.
Will try again tomorrow.

**Comment by yonguelink** [comment] 2024-05-08 11:27
I am running into the same issue. This morning, I couldn't get csharpier to boot up properly in VS, even after a few restart.

Starting the server on another terminal prompted me for network permissions, which I allowed, and ran on the same port as in Dennis' last screenshot. Then started VS and it booted _another_ server, as it connected to port `49153` instead of `49152` from the server running in the other terminal. Killed the server & VS, started VS again and csharpier seems fine, and connected to port `49152`.

This is very erratic on my end, hopefully allowing the network access will have fixed things... but if not, perhaps adding logs from the server in VS's debug output could help pinpoint the issue?

**Comment by Dennis-N8** [comment] 2024-05-09 08:51
So with or without global.json the CSharpier doesn't start when `dotnet csharpier --server` is running.

**Comment by Dennis-N8** [comment] 2024-05-09 08:52
But it started to work after I closed Visual studio, ran `dotnet tool update csharpier` and re-opened the Visual Studio.

**Comment by belav** [comment] 2024-05-10 16:05
When `dotnet csharpier --server` is run, it attempts to find an open port at 49152 or higher. If you run that from the terminal, the extension will start up a second instance of csharpier, which will find a different port and connect to that.

The extension has no way of knowing that an instance of csharpier was started already and is running which is why it may end up with a different port. Additionally the extension can be running multiple instances of csharpier, one per version. TLDR, the different/erratic port numbers is expected.

@yonguelink was the prompt you got like this?
![image](https://github.com/belav/csharpier/assets/3606529/c5752dc5-12ab-4df9-a045-8c327a45182e)

CSharpier binds kestrel to 127.0.0.1 which should avoid that. I was getting the popup initially when I was binding to "any" ipaddress.

Adding logging to the csharpier end is a good idea, getting it back into the extension is harder. But as long as it logs to a known location that would work.

I think for know I'm going to see if I can get the VS extension to try to find a port, and also add an option to completely bypass csharpier server. With VS trying to find the port it will be much easier to log/debug.

**Comment by yonguelink** [comment] 2024-05-10 16:38
Sorry for the picture of a screen - snipping tool didn't want to take the prompt in screenshot (probably due to elevated permissions?)

This is the prompt I got when starting csharpier via the terminal:

![image](https://github.com/belav/csharpier/assets/9469187/0dddd23f-deec-40f5-89f4-349bd968c8cf)

Note that the server doesn't seem to mind and just runs

![image](https://github.com/belav/csharpier/assets/9469187/55d019fb-c7ce-4044-b0da-d90ecfecd401)

Hitting cancel or allow has no effect on the actual behavior

I guess completely bypassing the server would be an effective workaround until the issue is found...

As a side note, I noticed that the issue happens pretty much all the time when I first boot my computer, but doesn't appear as often (if at all? I don't restart my IDEs that often outside of the daily reboot, but I haven't really noticed failure during those).

**Comment by belav** [comment] 2024-05-10 17:09
@yonguelink you probably have a version 0.27.x installed globally. That's the version that binds to 0.0.0.0, which causes the network popup. The extension will only run `--server` on 0.28.x

I have the changes I mentioned done and released as 1.7.3. I also realized that when `csharpier --server` was not responding with a port as expected that the extension wasn't reading from stderr, only stdout. Maybe that will help debug this issue.

The new option to skip csharpier server. I added the server option to make it easier to respond to the extension with information beyond just the contents of the formatted file. IE the server can respond with "this file is ignored, this file has compilation errors, etc". The older version that pipes the file back and forth still works and I don't foresee removing it.

**Comment by Dennis-N8** [comment] 2024-05-13 08:06
So I ran the `dotnet tool update csharpier` command and closed the Visual Studio 2 times.
Extension version 1.7.3

The output looks like this:

![image](https://github.com/belav/csharpier/assets/128690326/42d8bbc9-363c-43a8-820c-b028a2fef66e)

So the CSharpier server timed out, but when I selected to format the C# file - it did it.

**Comment by StefanSchoof** [comment] 2024-05-31 13:36
@mheguy-flo Thank you. Today csharpier did not work in VS and it drive me crazy. This fixed for me.

**Comment by belav** [comment] 2024-05-31 18:26
@mheguy-flo thanks for all the info, finally explains the random issues people are running into.

I did a basic test of this by finding a port windows had reserved, and modifying csharpier to use that port as the starting point. This did result in a failure.

I was toying with ideas for dealing with this and ran across a blog post that gave me a good idea - just let kestrel pick its own open port. It seems safe to assume that the aspnetcore team has solved the problem of finding a free port already.

I am thinking I'll modify the extensions to stop using csharpier server on 0.28.X to avoid anyone else running into this.

**Comment by Dennis-N8** [comment] 2024-06-05 09:10
We are waiting for a release))

**Comment by Dennis-N8** [comment] 2024-06-05 17:54
Result of `dotnet csharpier --server` command

![image](https://github.com/belav/csharpier/assets/128690326/b2ebd135-9c63-40e4-9057-286c0013860a)

**Comment by mheguy-flo** [comment] 2024-06-05 19:07
@Dennis-N8: There hasn't been a release to fix this issue yet. I suggest you check my comment above if you want a workaround.

**Comment by Dennis-N8** [comment] 2024-06-06 06:45
Oh, It helped, thank you)

> @Dennis-N8: There hasn't been a release to fix this issue yet. I suggest you check my comment above if you want a workaround.

**Closed** 2024-06-08 13:37 UTC

**Comment by Dennis-N8** [comment] 2024-06-09 11:36
![image](https://github.com/belav/csharpier/assets/128690326/16d7f2b4-1c1a-4896-87e8-fd10f2991a2b)

I just installed the new version of extension for Visual Studio.
Although it showed the Warning, it worked.
